### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by Xibalba1** [arzzen/exchangerate.host#3]
What are the rate limits for the historical rates data?

I am querying on a one-time basis for a lot of historical data and want to ensure I'm not abusing your service.

**Comment by arzzen** [comment]
Hi @Xibalba1 I understand, but why are you querying one-by-one when we have time-series endpoint (maximum date range one year)? You can query by year frame window instead of the number of days each year...

eg
https://api.exchangerate.host/timeseries?start_date=2019-01-01&end_date=2019-12-31

**Comment by Xibalba1** [comment]
This is much better. Thank you for steering me toward the light. And thank you for making and hosting this!
